name: Build

on:  
  workflow_call:
    outputs:
      artifacts:
        description: "Build artifacts information"
        value: ${{ jobs.building.outputs.artifacts }}
  push:
    branches:
      - live

jobs:

  testing:
    uses: ./.github/workflows/testing.yaml
  
  building:
    needs: testing
    outputs:
      artifacts: ${{ steps.build-info.outputs.artifacts }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_suffix: deb
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_suffix: dmg
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_suffix: msi
    runs-on: ${{ matrix.os }}
    steps:
      
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable

      - name: Install build dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install -y pkg-config
          fi 
        shell: bash

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release

      - name: Package application
        run: cargo packager --release --formats ${{ matrix.artifact_suffix }}

      - name: Set build info
        id: build-info
        run: |
          echo "artifacts=target/release/dist" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: palconnect-${{ matrix.os }}-${{ github.sha }}
          path: target/release/dist/
          retention-days: 30

