name: Run Rust Tests

on:
  workflow_call:
  push:
    branches:
      - live
      - canary
    tags:
      - v*.*.*
  pull_request:
    types:
      - review_requested

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2 # Cache build deps for faster building later.
      - name: Run tests
        run: cargo test
